name: EPZGameTurbo
options:
  bundleIdPrefix: com.epz.gameturbo
  deploymentTarget:
    iOS: 15.0
targets:
  EPZGameTurbo:
    type: application
    platform: iOS
    sources: [EPZGameTurbo]
    settings:
      CODE_SIGNING_ALLOWED: NO
      CODE_SIGN_IDENTITY: ""
      CODE_SIGNING_REQUIRED: NO
      INFOPLIST_FILE: EPZGameTurbo/Resources/Info.plist
